GH-46236: [Release][Packaging] Fix `dev/release/post-03-binary.sh` errors
There are two problems:

`with_read_timeout` can't set timeout:

    /host/binary-task.rb:463:in `with_read_timeout': undefined method `read_timeout' for nil:NilClass (NoMethodError)

          current_timeout = @http.read_timeout
                                 ^^^^^^^^^^^^^
            from /host/binary-task.rb:680:in `block in copy'
            from /host/binary-task.rb:442:in `with_retry'
            from /host/binary-task.rb:679:in `copy'
            from /host/binary-task.rb:1100:in `block (3 levels) in release'
            from /host/binary-task.rb:746:in `pull'
            from /host/binary-task.rb:1099:in `block (2 levels) in release'
            from /host/binary-task.rb:48:in `block (3 levels) in initialize'
            from /host/binary-task.rb:45:in `loop'
            from /host/binary-task.rb:45:in `block (2 levels) in initialize'

`yum:release` can't download a distribution:

    ArgumentError: wrong number of arguments (given 3, expected 4)
    /host/binary-task.rb:1266:in `download_distribution'
    /host/binary-task.rb:2129:in `block (3 levels) in define_yum_release_tasks'
    /host/binary-task.rb:2124:in `each'
    /host/binary-task.rb:2124:in `block (2 levels) in define_yum_release_tasks'

* Defer timeout set timing for `with_read_timeout`
* Add missing `type` argument for `yum:release`