msvc: doesn't capture constexpr value without default capture mode
https://github.com/apache/arrow/actions/runs/3603794502/jobs/6072417477#step:11:1242

D:\a\arrow\arrow\cpp\src\arrow/util/reflection_internal.h(280): error C3493: 'kUnderlyingMin' cannot be implicitly captured because no default capture mode has been specified
D:\a\arrow\arrow\cpp\src\arrow/util/reflection_internal.h(301): note: see reference to variable template 'const auto kEnumMembers<enum arrow::compute::CountOptions::CountMode>' being compiled
D:\a\arrow\arrow\cpp\src\arrow/compute/function_internal.h(95): note: see reference to function template instantiation 'std::string_view arrow::internal::enum_name<Enum>(Enum)' being compiled