GH-44728: [Python] Trigger manual Garbage collection before checking allocated bytes for dlpack tests (#44793)
### Rationale for this change

test_dlpack started failing for several jobs on CI due to our tests deallocating memory:
```
        allocated_bytes = pa.total_allocated_bytes()
        try:
            return f(*args, **kwargs)
        finally:
>           assert pa.total_allocated_bytes() == allocated_bytes
E           assert 3728 == 7440
```

### What changes are included in this PR?

Trigger a `gc.collect` before checking initial allocated bytes.

### Are these changes tested?

Yes via CI

### Are there any user-facing changes?

No

* GitHub Issue: #44728

Authored-by: Raúl Cumplido <raulcumplido@gmail.com>
Signed-off-by: Raúl Cumplido <raulcumplido@gmail.com>