ARROW-5159: [Rust] Unable to build benches in arrow crate.
After the refactor of kernel related files in ARROW-5116, the files in `bench` folder won't compile.

eg. 
```
error[E0432]: unresolved import `arrow::compute::boolean_kernels`
 --> arrow/benches/boolean_kernels.rs:26:5
 |
26 | use arrow::compute::boolean_kernels;
 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `boolean_kernels` in `compute`
```
This pr fixes these import errors.

Author: Zhiyuan Zheng <zhiyuan.zheng@yandex.com>

Closes #4138 from zhzy0077/fix/arrow-5159 and squashes the following commits:

3abacd80 <Zhiyuan Zheng> fix ARROW-5159: bench compile error.