ARROW-17086: [C++] Install java/dataset include file and fix debug build failed by compiler flag (#13614)
Arrow8 will install jni_util.h, but Arrow9 not, cause our project fail when upgraded to Arrow 9

And if use cmake --preset ninja-debug \
        -DARROW_BUILD_SHARED=ON \
        -DARROW_GANDIVA_JAVA=ON \
        -DARROW_GANDIVA=ON
it will failed with this error, fix it
arrow/cpp/src/gandiva/jni/expression_registry_helper.cc:157:78: error: implicit conversion loses integer precision: 'unsigned long' to 'int' [-Werror,-Wshorten-64-to-32]
  gandiva_data_types.SerializeToArray(reinterpret_cast<void*>(buffer.get()), size);

Lead-authored-by: Chengcheng Jin <chengcheng.jin@intel.com>
Co-authored-by: David Li <li.davidm96@gmail.com>
Signed-off-by: David Li <li.davidm96@gmail.com>