GH-51467: [CI][C++] Remove unused ranges include which breaks R build (#51469)
### Rationale for this change

After:
- https://github.com/apache/arrow/pull/49679

The nightly CI job for [test-r-macos-as-cran](https://github.com/ursacomputing/crossbow/actions/runs/35804144934/job/107001010915) failed due to ranges file not found:
```
 [ 95%] Building CXX object src/arrow/CMakeFiles/arrow_compute_objlib.dir/compute/kernels/vector_search_sorted.cc.o
/Users/runner/work/crossbow/crossbow/arrow/cpp/src/arrow/compute/kernels/vector_search_sorted.cc:23:10: fatal error: 'ranges' file not found
   23 | #include <ranges>
      |          ^~~~~~~~
1 error generated.
```

### What changes are included in this PR?

Remove `#include <ranges>` as is never used on the file.

### Are these changes tested?

Yes via CI

### Are there any user-facing changes?

No

### Was AI used for this PR?

In accordance to the [AI generation guidelines](https://arrow.apache.org/docs/dev/developers/overview.html#ai-generated-code), please disclose below whether and how AI was used in this PR.

**PR code and description written by:**

- [x] Human
- [ ] AI

**Reviewed before submission by:**

- [x] Human
- [ ] AI
- [ ] Not reviewed

* GitHub Issue: #51467

Authored-by: Raúl Cumplido <raulcumplido@gmail.com>
Signed-off-by: Raúl Cumplido <raulcumplido@gmail.com>