ARROW-18121: [Release][CI] Use Ubuntu 22.04 for verifying binaries
APT/Yum verifications use Docker. If we use old libseccomp on host,
some operations may cause errors:

https://github.com/ursacomputing/crossbow/actions/runs/3294870946/jobs/5432835953#step:7:5437

    + valac --pkg arrow-glib --pkg posix build.vala
    error: Failed to close file descriptor for child process (Operation not permitted)
    error: Failed to close file descriptor for child process (Operation not permitted)
    error: Failed to close file descriptor for child process (Operation not permitted)
    error: Failed to close file descriptor for child process (Operation not permitted)
    error: Failed to close file descriptor for child process (Operation not permitted)
    error: Failed to close file descriptor for child process (Operation not permitted)