MINOR: [C++] Fix compilation error in hash_join_benchmark (#34000)
### Rationale for this change

[`HashJoinImpl::Init`](https://github.com/apache/arrow/blob/master/cpp/src/arrow/compute/exec/hash_join.h#L51) expects `output_batch_callback` and `finished_callback` to return `Status`, while the currently passed arguments return void. It caused compilation errors on my machine. 

```
error: cannot convert ‘arrow::compute::JoinBenchmark::JoinBenchmark(arrow::compute::BenchmarkSettings&)::<lambda(int64_t, arrow::compute::ExecBatch)>’ to ‘arrow::compute::HashJoinImpl::OutputBatchCallback’ {aka ‘std::function<arrow::Status(long int, arrow::compute::ExecBatch)>’}
```

### What changes are included in this PR?

Fix the return types.

### Are these changes tested?

Yes. It fixes the compilation error on my machine.

### Are there any user-facing changes?

No.

Authored-by: Jin Shang <shangjin1997@gmail.com>
Signed-off-by: Sutou Kouhei <kou@clear-code.com>