ARROW-17536: [Packaging][RPM][Gandiva] Fix build error on CentOS Stream 9
LLVM is built with gcc-toolset-12 and it can't be used with the
default g++. We also need to use gcc-toolset-12.

Error message:

    /usr/bin/ld: .../libgandiva.so.1000: undefined reference to
    `std::__glibcxx_assert_fail(char const*, int, char const*, char const*)'