ARROW-4260: [Python] NumPy buffer protocol failure
The following error only occurred when both numpy=1.16 and pickle5 was installed.
It's a numpy issue https://github.com/numpy/numpy/issues/12745, so skipping the test until it's resolved.

```
====================================================== FAILURES =======================================================
__________________________________________ test_serialize_deserialize_pandas __________________________________________
ValueError: cannot include dtype 'M' in a buffer

The above exception was the direct cause of the following exception:

    def test_serialize_deserialize_pandas():
        # ARROW-1784, serialize and deserialize DataFrame by decomposing
        # BlockManager
        df = _fully_loaded_dataframe_example()
>       _check_serialize_components_roundtrip(df)

pyarrow/tests/test_convert_pandas.py:2278:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pyarrow/tests/test_convert_pandas.py:2268: in _check_serialize_components_roundtrip
    components = ctx.serialize(df).to_components()
pyarrow/serialization.pxi:198: in pyarrow.lib.SerializationContext.serialize
    return serialize(obj, context=self)
pyarrow/serialization.pxi:345: in pyarrow.lib.serialize
    check_status(SerializeObject(context, wrapped_value, &serialized.data))
pyarrow/serialization.pxi:153: in pyarrow.lib.SerializationContext._serialize_callback
    serialized_obj = {"data": self.custom_serializers[type_id](obj)}
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

x = MultiIndex(levels=[[2000-01-01 00:00:00, 2000-01-02 00:00:00, 2000-01-03 00:00:00, 2000-01-04 00:00:00, 2000-01-05 00:00:00], ['bar', 'foo']],
           labels=[[0, 0, 1, 1, 2, 2, 3, 3, 4, 4], [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]])

    def _pickle_to_buffer(x):
>       pickled = builtin_pickle.dumps(x, protocol=builtin_pickle.HIGHEST_PROTOCOL)
E       SystemError: <built-in function __import__> returned a result with an error set
```

Author: Krisztián Szűcs <szucs.krisztian@gmail.com>

Closes #3403 from kszucs/travis_numpy_version and squashes the following commits:

e3162a8b <Krisztián Szűcs> pin to minor
77e9b64f <Krisztián Szűcs> reason
301226d1 <Krisztián Szűcs> skip serialize test
39a7161d <Krisztián Szűcs> appveyor
ae1f16d9 <Krisztián Szűcs> pin numpy to 1.14