[C++] Fix build error on Ubuntu 16.04
Formatted error message:

    FAILED: /usr/bin/ccache /usr/lib/ccache/g++ \
      -DARROW_JEMALLOC \
      -DARROW_JEMALLOC_INCLUDE_DIR="" \
      -DARROW_USE_GLOG \
      -DARROW_USE_SIMD \
      -DARROW_WITH_BOOST_FILESYSTEM \
      -DARROW_WITH_BROTLI \
      -DARROW_WITH_BZ2 \
      -DARROW_WITH_LZ4 \
      -DARROW_WITH_SNAPPY \
      -DARROW_WITH_ZLIB \
      -DGTEST_LINKED_AS_SHARED_LIBRARY=1 \
      -DURI_STATIC_BUILD \
      -isystem /arrow/cpp/thirdparty/flatbuffers/include \
      -isystem boost_ep-prefix/src/boost_ep \
      -isystem thrift_ep/src/thrift_ep-install/include \
      -isystem /arrow/cpp/thirdparty/protobuf_ep-install/include \
      -isystem jemalloc_ep-prefix/src \
      -isystem googletest_ep-prefix/src/googletest_ep/include \
      -isystem rapidjson_ep/src/rapidjson_ep-install/include \
      -isystem /arrow/cpp/thirdparty/hadoop/include \
      -Isrc \
      -I/arrow/cpp/src \
      -I/arrow/cpp/src/generated \
      -fdiagnostics-color=always \
      -ggdb \
      -O0 \
      -Wall \
      -Wno-conversion \
      -Wno-sign-conversion \
      -Wno-unused-variable \
      -Werror \
      -Wno-attributes \
      -msse4.2 \
      -g \
      -fPIE \
      -pthread \
      -std=gnu++11 \
      -MMD \
      -MT src/arrow/dataset/CMakeFiles/arrow-dataset-dataset-test.dir/dataset_test.cc.o \
      -MF src/arrow/dataset/CMakeFiles/arrow-dataset-dataset-test.dir/dataset_test.cc.o.d \
      -o src/arrow/dataset/CMakeFiles/arrow-dataset-dataset-test.dir/dataset_test.cc.o \
      -c /arrow/cpp/src/arrow/dataset/dataset_test.cc
    /arrow/cpp/src/arrow/dataset/dataset_test.cc: In member function
      'virtual void arrow::dataset::TestSchemaUnification_SelectStar_Test::TestBody()':
    /arrow/cpp/src/arrow/dataset/dataset_test.cc:531:3: error:
      converting to '
        std::tuple<nonstd::optional_lite::optional<int>,
                   nonstd::optional_lite::optional<int>,
                   nonstd::optional_lite::optional<int>,
                   nonstd::optional_lite::optional<int>,
                   nonstd::optional_lite::optional<int>,
                   nonstd::optional_lite::optional<int> >'
      from initializer list would use explicit constructor '
        constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...)
          [with
           _UElements = {
             int,
             int,
             const nonstd::optional_lite::nullopt_t&,
             const nonstd::optional_lite::nullopt_t&,
             int,
             int
           };
           <template-parameter-2-2> = void;
           _Elements = {
             nonstd::optional_lite::optional<int>,
             nonstd::optional_lite::optional<int>,
             nonstd::optional_lite::optional<int>,
             nonstd::optional_lite::optional<int>,
             nonstd::optional_lite::optional<int>,
             nonstd::optional_lite::optional<int>
           }]'
       };
       ^

Full log: https://circleci.com/gh/ursa-labs/crossbow/6109