GH-44655: [C++][Python] Enable building AzureFileSystem in PyArrow wheels on Windows (#49170)
### Rationale for this change
This PR is a follow up to #48971 and should address #44655. Previously, the C++ AzureFileSystem couldn't be compiled on Windows due to a incomplete type definition. Now that this has been resolved, we should be able to enable building on the Windows Platform for PyArrow as well.

### What changes are included in this PR?
This PR sets the flags to enable building AzureFileSystem for PyArrow wheels on Windows. This will bring functionality in line with the Linux and macOS wheel builds.

### Are these changes tested?
These changes enable existing testing that's used for other C++ Filesystems in PyArrow. Tests will validate the class is importable from the built wheels which seems to be the existing precedent. I can add other tests if needed, but will likely need some direction.

### Are there any user-facing changes?
This PR will enable use of AzureFileSystem on Windows. Currently, trying to use or import the AzureFileSystem from PyArrow raises an ArrowNotImplementedError.

```python
>>> from pyarrow.fs import AzureFileSystem
ImportError: The pyarrow installation is not built with support for 'AzureFileSystem'
```

```python
>>> import pyarrow.fs as fs
>>> fs.FileSystem.from_uri('abfss://container@ account.dfs.core.windows.net/path')
pyarrow.lib.ArrowNotImplementedError: Got Azure Blob File System URI but Arrow compiled without Azure Blob File System support
```

After these changes, support should be available.
* GitHub Issue: #44655

Lead-authored-by: Nate Prewitt <nate.prewitt@gmail.com>
Co-authored-by: Sutou Kouhei <kou@cozmixng.org>
Co-authored-by: Sutou Kouhei <kou@clear-code.com>
Signed-off-by: Sutou Kouhei <kou@clear-code.com>