ARROW-9224: [Dev][Archery] clone local source with --shared
`archery benchmark diff` runs "git clone --local" to clone source code
to /tmp. If /tmp and source directory are at different disk volumes, it
fails because "git clone --local" uses hard links which only works on
same volume. This patch replaces "--local" with "--shared".

Error log:
fatal: failed to create link '/tmp/arrow-archery-lwm7k6wm/origin_master/arrow/.git/objects/2d/80a4d2da431dbfe3c736b6349eb4a0bcb6ece5': Invalid cross-device link
subprocess.CalledProcessError: Command '['git', 'clone', '--local', PosixPath('/home/cyb/arrow'), '/tmp/arrow-archery-lwm7k6wm/origin_master/arrow']' returned non-zero exit status 128.