Avoid loading simd_load_set_invalid which doesn't exist on aarch64
    error[E0432]: unresolved import `crate::compute::util::simd_load_set_invalid`
    --> /home/tyler/.cargo/git/checkouts/arrow-3a9cfebb6b7b2bdc/2a8e37d/rust/arrow/src/compute/kernels/arithmetic.rs:42:5
    |
    42 | use crate::compute::util::simd_load_set_invalid;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `simd_load_set_invalid` in `compute::util`

    Compiling thiserror v1.0.16
    error: aborting due to previous error