GH-45055: [C++][Flight] Update Flight Server RecordBatchStreamImpl to reuse ipc::RecordBatchWriter with custom IpcPayloadWriter instead of manually generating FlightPayload (#47115)
### Rationale for this change

Currently Dictionary replacement or deltas are not supported in DoGet as seen on the original issue.
We could replicate the `ipc::WriteDictionaries` code but instead of replicating this logic we can also update our flight server `RecordBatchStreamImpl` to reuse `ipc::RecordBatchWriter` and just update the payload to match the flight payload.

### What changes are included in this PR?

Updated logic on `arrow::flight::RecordBatchStream::RecordBatchStreamImpl` to use an `ipc::RecordBatchWriter` and a custom `ipc::IpcPayloadWriter` instead of manually buidling the payloads.

### Are these changes tested?

Yes via CI. Test data for some Python tests has been updated to validate dictionary replacement is working now. On main the updated test fails with:
```python
>               assert data.equals(table)
E               assert False
E                +  where False = equals(pyarrow.Table\nsome_dicts: dictionary<values=string, indices=int64, ordered=0>\n----\nsome_dicts: [  -- dictionary:\n["foo...\n[1,0,null],  -- dictionary:\n["foo","baz","quux"]  -- indices:\n[2,1],  -- dictionary:\n["bar","qux"]  -- indices:\n[0,1]])
E                +    where equals = pyarrow.Table\nsome_dicts: dictionary<values=string, indices=int64, ordered=0>\n----\nsome_dicts: [  -- dictionary:\n["foo...ull],  -- dictionary:\n["foo","baz","quux"]  -- indices:\n[2,1],  -- dictionary:\n["foo","baz","quux"]  -- indices:\n[0,1]].equals

pyarrow/tests/test_flight.py:1319: AssertionError
================================================================================== short test summary info ===================================================================================
FAILED pyarrow/tests/test_flight.py::test_flight_do_get_dicts - assert False
FAILED pyarrow/tests/test_flight.py::test_flight_domain_socket - assert False

```

### Are there any user-facing changes?

No

* GitHub Issue: #45055

Authored-by: Raúl Cumplido <raulcumplido@gmail.com>
Signed-off-by: David Li <li.davidm96@gmail.com>