GH-51210: [C++] Initialize `output_` on empty `select_k` inputs (#51212)
### Rationale for this change

This fixes possible crashes of `SelectKUnstable` if inputs were empty

### What changes are included in this PR?

This includes the bug fix and test cases which cover the broken prior behavior.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

**This PR contains a "Critical Fix".**:
(c) a bug that causes a crash

If `SelectKUnstable` is called on an empty table or chunked-array the process terminates with the exception `std::bad_variant_access`.

Through python, the wrapping of the (invalid) Datum in a python object already fails with the following error message:
```
ValueError: Unable to wrap Datum in a Python object
```
* GitHub Issue: #51210

Authored-by: Alexander Taepper <alexander.taepper@gmail.com>
Signed-off-by: Antoine Pitrou <antoine@python.org>