ARROW-17992: [CI][C++][Conda] Remove needless clangdev/llvmdev pinnings
We need clang 11 or later for Gandiva.

https://dev.azure.com/ursacomputing/crossbow/_build/results?buildId=37098&view=logs&j=4c86bc1b-1091-5192-4404-c74dfaad23e7&t=41795ef0-6501-5db4-3ad4-33c0cf085626&l=1001

    [6/94] Generating decimal_ops.bc
    FAILED: src/gandiva/precompiled/decimal_ops.bc
    D:/bld/arrow-cpp-ext_1665469353844/work/cpp/build/src/gandiva/precompiled/decimal_ops.bc
    cmd.exe /C "cd /D
    D:\bld\arrow-cpp-ext_1665469353844\work\cpp\build\src\gandiva\precompiled
    && D:\bld\arrow-cpp-ext_1665469353844\_h_env\Library\bin\clang.exe
    -std=c++17 -fms-compatibility -fms-compatibility-version=19.20
    -DGANDIVA_IR -DNDEBUG -DARROW_STATIC -DGANDIVA_STATIC
    -fno-use-cxa-atexit -emit-llvm -O3 -c
    D:/bld/arrow-cpp-ext_1665469353844/work/cpp/src/gandiva/precompiled/decimal_ops.cc
    -o
    D:/bld/arrow-cpp-ext_1665469353844/work/cpp/build/src/gandiva/precompiled/decimal_ops.bc
    -ID:/bld/arrow-cpp-ext_1665469353844/work/cpp/src
    -ID:/bld/arrow-cpp-ext_1665469353844/work/cpp/build/src
    -ID:/bld/arrow-cpp-ext_1665469353844/_h_env/Library/include"
    In file included from
    D:/bld/arrow-cpp-ext_1665469353844/work/cpp/src/gandiva/precompiled/decimal_ops.cc:20:
    In file included from
    D:/bld/arrow-cpp-ext_1665469353844/work/cpp/src\gandiva/precompiled/decimal_ops.h:20:
    In file included from C:\Program Files (x86)\Microsoft Visual
    Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\cstdint:9:
    C:\Program Files (x86)\Microsoft Visual
    Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\yvals_core.h:571:2:
    error: STL1000: Unexpected compiler version, expected Clang 11.0.0
    or newer.
    #error STL1000: Unexpected compiler version, expected Clang 11.0.0 or newer.
     ^

This was added by me in #13892 but I can't remember why I pinned to
10...