GH-15134: [Ruby] Specify -mmacox-version-min=10.14 explicitly for old Xcode
This suppresses the following error with old Xcode:

    /tmp/local/include/arrow/type.h:1745:36: error:
    'get<arrow::FieldPath, arrow::FieldPath, std::string,
    std::vector<arrow::FieldRef>>' is unavailable: introduced in macOS
    10.13
        if (IsFieldPath()) return std::get<FieldPath>(impl_).indices().size() > 1;
                                       ^