ARROW-15447: [C++] Avoid conflict between ORC options API and glibc-defined macro
Fix the following compilation error on Ubuntu 18.04:
```
/arrow/cpp/src/arrow/adapters/orc/options.h:73:13: error: In the GNU C Library, "major" is defined
 by <sys/sysmacros.h>. For historical compatibility, it is
 currently defined by <sys/types.h> as well, but we plan to
 remove this soon. To use "major", include <sys/sysmacros.h>
 directly. If you did not intend to use a system-defined macro
 "major", you should undefine it after including <sys/types.h>. [-Werror]
   int32_t major() const { return this->major_version; }
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```