Suppress sign-compare warnings from g++
e.g.:

    In file included from /arrow/cpp/src/arrow/testing/gtest_util.h:31,
                     from /arrow/cpp/src/arrow/io/test_common.cc:35:
    /build/cpp/googletest_ep-prefix/include/gtest/gtest.h: In instantiation of 'testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = long int; T2 = long unsigned int]':
    /build/cpp/googletest_ep-prefix/include/gtest/gtest.h:1564:23:   required from 'static testing::AssertionResult testing::internal::EqHelper::Compare(const char*, const char*, const T1&, const T2&) [with T1 = long int; T2 = long unsigned int; typename std::enable_if<((! std::is_integral<_Tp>::value) || (! std::is_pointer<_Dp>::value))>::type* <anonymous> = 0]'
    /arrow/cpp/src/arrow/io/test_common.cc:47:3:   required from here
    /build/cpp/googletest_ep-prefix/include/gtest/gtest.h:1545:11: error: comparison of integer expressions of different signedness: 'const long int' and 'const long unsigned int' [-Werror=sign-compare]
     1545 |   if (lhs == rhs) {
          |       ~~~~^~~~~~