Use self-defined macro
ARROW_RETURN_NOT_OK gives an error
error C2440: 'return': cannot convert from 'arrow::Status' to 'int'
/arrow/cpp/src/arrow/status.h:45:21: error: cannot convert 'arrow::Status' to 'int' in return
   45 |       return (status);