GH-50868: [C++][CI] Suppress deprecated Abseil API warnings for GCS on macOS (#50887)
### Rationale for this change

Around August 10, 2026, the `ARM64 macOS GLib & Ruby` job in this project started failing.

The failure appears to have been caused by the Abseil version used when building the bundled google-cloud-cpp on macOS being updated to `20260526.0`.

https://github.com/Homebrew/homebrew-core/blob/3decf2e9073cb08af3b4d5be7623f333f41fa3cc/Formula/a/abseil.rb

In Abseil LTS `20260526.0`, many polyfill types and related APIs provided for pre-C++17 environments were marked as deprecated. Users are encouraged to migrate to the corresponding C++ standard library APIs.

https://github.com/abseil/abseil-cpp/releases/tag/20260526.0

The build failure occurs at the following code in google-cloud-cpp:

```cpp
/Users/runner/work/arrow/arrow/build/cpp/_deps/google_cloud_cpp-src/google/cloud/stream_range.h:208:11: error: 'visit<UnpackVariant, std::variant<google::cloud::Status, google::cloud::storage::ObjectMetadata>>' is deprecated [-Werror,-Wdeprecated-declarations]
  208 |     absl::visit(UnpackVariant{*this}, std::move(v));
      |           ^
```

`absl::visit` has not been removed, but using it with Abseil `20260526.0` produces a deprecation warning. This would normally remain a warning, but Apache Arrow's CI uses `-Werror`, which causes the deprecation warning to be treated as a compilation error.

For C++17 and later, using `std::visit` is recommended:

```cpp
std::visit(UnpackVariant{*this}, std::move(v));
```

However, `absl::visit` is still used in the latest google-cloud-cpp source.

https://github.com/googleapis/google-cloud-cpp/blob/main/google/cloud/stream_range.h#L206-L208

A fundamental fix will likely be required in google-cloud-cpp.

### What changes are included in this PR?

* Add `-Wno-error=deprecated-declarations` to avoid build failures caused by deprecation warnings.
* Skip the red-arrow-flight tests on macOS because they currently fail. This will be addressed in a separate issue.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

No.

* GitHub Issue: #50868

Lead-authored-by: Hiroyuki Sato <hiroysato@gmail.com>
Co-authored-by: Sutou Kouhei <kou@cozmixng.org>
Signed-off-by: Sutou Kouhei <kou@clear-code.com>