ARROW-7260: [CI] Remove Ubuntu 14.04 test job
https://circleci.com/gh/ursa-labs/crossbow/5329

    /arrow/cpp/src/arrow/dataset/filter_test.cc:80:194: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Werror=literal-suffix]
       ASSERT_EQ("a"_.ToString(), "a");
                    ^

We drop support for Ubuntu 14.04 because it reaches EOL.

Closes #5901 from kou/ci-ubuntu-14.04 and squashes the following commits:

26c60e528 <Sutou Kouhei> Remove Ubuntu 14.04 CI job
3cf677232 <Sutou Kouhei> Disable ARROW_DATASET
dcf017a7f <Sutou Kouhei> ARROW-7260:  Fix Ubuntu 14.04 test job

Authored-by: Sutou Kouhei <kou@clear-code.com>
Signed-off-by: Sutou Kouhei <kou@clear-code.com>