GH-35021: [Python][CI] Use conda's gdb in test-conda-python
If we use system gdb, we can't import build-in libraries such as math:

    (gdb) source /arrow/cpp/gdb_arrow.py
    Traceback (most recent call last):
      File "/arrow/cpp/gdb_arrow.py", line 20, in <module>
        import datetime
      File "/usr/lib/python3.10/datetime.py", line 12, in <module>
        import math as _math
    ModuleNotFoundError: No module named 'math'

Because system gdb is built with system Python not conda's Python.