ARROW-11997: [Python] concat_tables crashes python interpreter
Before:

>>> import pyarrow
>>> pyarrow.concat_tables([None])
Bus error: 10
Python quit unexpectedly

After:

>>> import pyarrow
>>> pyarrow.concat_tables([None])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/table.pxi", line 2229, in pyarrow.lib.concat_tables
    raise TypeError("Unable to concatenate table. Table is None.")
TypeError: Unable to concatenate table. Table is None.