GH-35501: [C++] Fix error C2280 in MSVC (#35683)
### Rationale for this change
Arrow failed to build with error C2280 under MSVC cpplatest mode, because std::basic_string::basic_string(std::nullptr_t) is deleted since C++23. So, using `std::basic_string::basic_string("")` to replace `std::basic_string::basic_string(std::nullptr_t)` to fix this issue. 

Related issue: #35501 

### What changes are included in this PR?

### Are these changes tested?

### Are there any user-facing changes?

* Closes: #35501

Authored-by: June Liu (Beyondsoft Corporation) <v-juneliu@microsoft.com>
Signed-off-by: Sutou Kouhei <kou@clear-code.com>