GH-34308: [CI][C++] Use str("") to reset std::stringstream for old g++
    FAILED: src/arrow/CMakeFiles/arrow-array-test.dir/array/array_run_end_test.cc.o
    g++ ... -std=c++17 -c /arrow/cpp/src/arrow/array/array_run_end_test.cc
    /arrow/cpp/src/arrow/array/array_run_end_test.cc: In member
    function 'virtual void
    arrow::{anonymous}::TestRunEndEncodedArray_Printing_Test::TestBody()':
    /arrow/cpp/src/arrow/array/array_run_end_test.cc:580:9: error:
    converting to 'std::__cxx11::basic_stringstream<char>' from
    initializer list would use explicit constructor
    'std::__cxx11::basic_stringstream<
       _CharT,
       _Traits,
       _Alloc
     >::basic_stringstream(std::ios_base::openmode)
     [with _CharT = char;
           _Traits = std::char_traits<char>;
           _Alloc = std::allocator<char>;
            std::ios_base::openmode = std::_Ios_Openmode]' [-Werror]
       ss = {};
             ^
    ...
    cc1plus: all warnings being treated as errors